// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductDeal struct {
	ID             pgtype.UUID        `json:"id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	DealPrice      int32              `json:"deal_price"`
	DealStock      int32              `json:"deal_stock"`
	RemainingStock int32              `json:"remaining_stock"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ProductProduct struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       int32              `json:"price"`
	Stock       int32              `json:"stock"`
	Category    pgtype.Text        `json:"category"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
