// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveDeals(ctx context.Context, startsAt pgtype.Timestamptz) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsByCategory(ctx context.Context, category pgtype.Text) (int64, error)
	// Deal queries
	CreateDeal(ctx context.Context, arg CreateDealParams) (ProductDeal, error)
	// Product queries
	CreateProduct(ctx context.Context, arg CreateProductParams) (ProductProduct, error)
	GetDealByID(ctx context.Context, id pgtype.UUID) (GetDealByIDRow, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (ProductProduct, error)
	GetStockForUpdate(ctx context.Context, id pgtype.UUID) (GetStockForUpdateRow, error)
	ListActiveDeals(ctx context.Context, arg ListActiveDealsParams) ([]ListActiveDealsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ProductProduct, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ProductProduct, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (ProductProduct, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (UpdateStockRow, error)
}

var _ Querier = (*Queries)(nil)
