openapi: 3.0.4
info:
  title: Auth Service API
  description: 사용자 인증 및 JWT 토큰 관리 서비스
  version: 1.0.0
  contact:
    name: Flash Deal Team

servers:
  - url: http://localhost:8001
    description: Local development server

tags:
  - name: auth
    description: 인증 관련 API
  - name: users
    description: 사용자 관리 API

paths:
  /health:
    get:
      summary: 헬스 체크
      operationId: healthCheck
      responses:
        "200":
          description: 서비스 정상
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /auth/register:
    post:
      tags:
        - auth
      summary: 회원가입
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: 회원가입 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: 이미 존재하는 이메일
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/login:
    post:
      tags:
        - auth
      summary: 로그인
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/refresh:
    post:
      tags:
        - auth
      summary: 토큰 갱신
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
      responses:
        "200":
          description: 토큰 갱신 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: 유효하지 않은 리프레시 토큰
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/verify:
    get:
      tags:
        - auth
      summary: 토큰 검증
      description: Gateway에서 JWT 토큰 유효성 검증에 사용
      operationId: verifyToken
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 토큰 유효
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyResponse"
        "401":
          description: 유효하지 않은 토큰
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/me:
    get:
      tags:
        - users
      summary: 내 정보 조회
      operationId: getMyProfile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "401":
          description: 인증 필요
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - service
      properties:
        status:
          type: string
          example: healthy
        service:
          type: string
          example: auth-service

    RegisterRequest:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: securepassword123
        name:
          type: string
          minLength: 2
          maxLength: 50
          example: 홍길동

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: securepassword123

    RefreshRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

    TokenResponse:
      type: object
      required:
        - access_token
        - refresh_token
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          description: 액세스 토큰 만료 시간(초)
          example: 3600

    VerifyResponse:
      type: object
      required:
        - valid
        - user_id
      properties:
        valid:
          type: boolean
          example: true
        user_id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000

    UserResponse:
      type: object
      required:
        - id
        - email
        - name
        - created_at
      properties:
        id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        email:
          type: string
          format: email
          example: user@example.com
        name:
          type: string
          example: 홍길동
        created_at:
          type: string
          format: date-time
          example: 2024-01-15T09:30:00Z

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: VALIDATION_ERROR
        message:
          type: string
          example: 이메일 형식이 올바르지 않습니다.
        details:
          type: object
          additionalProperties: true
