_format_version: "3.0"
_transform: true

# ===================
# Consumers & JWT Credentials
# ===================
consumers:
  - username: flash-deals-api
    jwt_secrets:
      - key: flash-deals
        secret: your-secret-key-change-in-production
        algorithm: HS256

# ===================
# Services
# ===================
services:
  # ===================
  # Auth Service
  # ===================
  - name: auth-service
    url: http://auth:8001
    routes:
      # Public routes (인증 불필요)
      - name: auth-public-routes
        paths:
          - /auth/register
          - /auth/login
          - /auth/refresh
          - /auth/health
        strip_path: false
      # Protected routes (JWT 검증 필요)
      - name: auth-protected-routes
        paths:
          - /auth/users
          - /auth/verify
        strip_path: false

  # ===================
  # Product Service
  # ===================
  - name: product-service
    url: http://product:8002
    routes:
      - name: product-routes
        paths:
          - /products
        strip_path: false

  # ===================
  # Order Service
  # ===================
  - name: order-service
    url: http://order:8003
    routes:
      - name: order-routes
        paths:
          - /orders
        strip_path: false

plugins:
  # ===================
  # JWT Plugin (Protected Routes)
  # ===================
  - name: jwt
    route: auth-protected-routes
    config:
      claims_to_verify:
        - exp

  # ===================
  # JWT Plugin (Order Routes)
  # ===================
  - name: jwt
    route: order-routes
    config:
      claims_to_verify:
        - exp

  # ===================
  # Proxy Cache (Protected Routes)
  # ===================
  - name: proxy-cache
    route: auth-protected-routes
    config:
      strategy: memory
      content_type:
        - application/json
      cache_ttl: 300  # 5분 캐싱
      vary_headers:
        - Authorization  # JWT별로 캐싱 (사용자별 분리)

  # ===================
  # Global Plugins
  # ===================
  - name: opentelemetry
    config:
      traces_endpoint: http://otel-collector:4318/v1/traces
      resource_attributes:
        service.name: gateway
        service.namespace: flash-deals
        deployment.environment: development
      propagation:
        default_format: w3c

  - name: prometheus
    config:
      per_consumer: false
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true
