// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrdersOrderStatus string

const (
	OrdersOrderStatusPending   OrdersOrderStatus = "pending"
	OrdersOrderStatusConfirmed OrdersOrderStatus = "confirmed"
	OrdersOrderStatusShipped   OrdersOrderStatus = "shipped"
	OrdersOrderStatusDelivered OrdersOrderStatus = "delivered"
	OrdersOrderStatusCancelled OrdersOrderStatus = "cancelled"
)

func (e *OrdersOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersOrderStatus(s)
	case string:
		*e = OrdersOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersOrderStatus: %T", src)
	}
	return nil
}

type NullOrdersOrderStatus struct {
	OrdersOrderStatus OrdersOrderStatus `json:"orders_order_status"`
	Valid             bool              `json:"valid"` // Valid is true if OrdersOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersOrderStatus), nil
}

type OrdersOrder struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TotalAmount   int32              `json:"total_amount"`
	Status        OrdersOrderStatus  `json:"status"`
	RecipientName pgtype.Text        `json:"recipient_name"`
	Phone         pgtype.Text        `json:"phone"`
	Address       pgtype.Text        `json:"address"`
	AddressDetail pgtype.Text        `json:"address_detail"`
	PostalCode    pgtype.Text        `json:"postal_code"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason  pgtype.Text        `json:"cancel_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OrdersOrderItem struct {
	ID          pgtype.UUID        `json:"id"`
	OrderID     pgtype.UUID        `json:"order_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	DealID      pgtype.UUID        `json:"deal_id"`
	ProductName string             `json:"product_name"`
	Quantity    int32              `json:"quantity"`
	UnitPrice   int32              `json:"unit_price"`
	Subtotal    int32              `json:"subtotal"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
