// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelOrder(ctx context.Context, arg CancelOrderParams) (OrdersOrder, error)
	CountOrdersByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountOrdersByUserIDAndStatus(ctx context.Context, arg CountOrdersByUserIDAndStatusParams) (int64, error)
	// Order queries
	CreateOrder(ctx context.Context, arg CreateOrderParams) (OrdersOrder, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrdersOrderItem, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (OrdersOrder, error)
	GetOrderForUpdate(ctx context.Context, id pgtype.UUID) (GetOrderForUpdateRow, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrdersOrderItem, error)
	ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]OrdersOrder, error)
	ListOrdersByUserIDAndStatus(ctx context.Context, arg ListOrdersByUserIDAndStatusParams) ([]OrdersOrder, error)
	// N+1 문제 해결: 주문 + 아이템을 한 번에 조회
	ListOrdersWithItemsByUserID(ctx context.Context, arg ListOrdersWithItemsByUserIDParams) ([]ListOrdersWithItemsByUserIDRow, error)
	ListOrdersWithItemsByUserIDAndStatus(ctx context.Context, arg ListOrdersWithItemsByUserIDAndStatusParams) ([]ListOrdersWithItemsByUserIDAndStatusRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (OrdersOrder, error)
}

var _ Querier = (*Queries)(nil)
